project:
  type: book
  output-dir: docs

book:
  title: "Automatyczna analiza obrazu"
  reader-mode: true
  page-footer:
    left: |
      Automatyczna analiza obrazu, Dariusz Majerek
    right: |
      Ta książka została napisana z wykorzystaniem <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  repo-url: https://github.com/dax44/ComputerVision/
  repo-actions: [issue]
  author:
  - name: Dariusz Majerek
    url: d.majerek@pollub.pl
    affiliation: Politechnika Lubelska
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib


format:
  html:
    theme:
      - cosmo
      - mycss.scss
    code-link: true

    author-meta: "Dariusz Majerek"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual
