project:
  type: book
  output-dir: docs

book:
  title: "Automatyczna analiza obrazu"
  reader-mode: true
  language: setup/polski.yml
  page-footer:
    left: |
      Automatyczna analiza obrazu, Dariusz Majerek
    right: |
      Książka została napisana w <a href="https://quarto.org/">Quarto</a>
  cover-image: cover.png
  favicon: cover.png
  repo-url: https://github.com/dax44/ComputerVision/
  repo-actions: [issue]
  sharing: [twitter,facebook]
  downloads: [pdf, epub]
  search: true
  twitter-card:
    site: "@DariuszMajerek"
  author: 
  - name: Dariusz Majerek
    affiliation: Politechnika Lubelska
  date: last-modified
  sidebar: 
    logo: images/logo.png
  chapters:
    - index.qmd
    - intro.qmd
    - history.qmd
    - digt_img.qmd
    - transformations.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
reference-location: margin

format:
  html:
    lang: pl
    theme:
      light: [pulse, mycss.scss]
      dark: [slate, mycss.scss]
    code-link: true
    code-fold: true
    margin-left: 0em
    margin-right: 0em
execute: 
  warning: false

editor: visual
comments:
  hypothesis: true
